/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddFriendDialog: typeof import('./src/components/AddFriendDialog.vue')['default']
    ChatInterface: typeof import('./src/components/ChatInterface.vue')['default']
    ContactInfo: typeof import('./src/components/ContactInfo.vue')['default']
    ContactList: typeof import('./src/components/ContactList.vue')['default']
    ContactSelector: typeof import('./src/components/ContactSelector.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FriendChatTest: typeof import('./src/components/FriendChatTest.vue')['default']
    FriendRequestsDialog: typeof import('./src/components/FriendRequestsDialog.vue')['default']
    FriendsPage: typeof import('./src/components/FriendsPage.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    OfflineMessageTest: typeof import('./src/components/OfflineMessageTest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
    WebSocketTest: typeof import('./src/components/WebSocketTest.vue')['default']
  }
}
