-- 二进制图片存储表
CREATE TABLE IF NOT EXISTS images (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '图片ID',
  content_type VARCHAR(100) NOT NULL COMMENT 'MIME类型',
  data LONGBLOB NOT NULL COMMENT '二进制数据',
  size BIGINT NOT NULL COMMENT '大小(字节)',
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='二进制图片表';