# Spring Boot 应用配置
spring:
  application:
    name: chat-backend
  
  # 数据源配置（使用MySQL数据库）
  datasource:
    url: jdbc:mysql://localhost:3306/chat_app?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    # 连接池配置
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # 数据库初始化配置（禁用自动创建表）
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
  
  # MyBatis配置（必需配置）
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.chatapp.entity
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  
  # Redis配置（可选）
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      jedis:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: -1ms
  
  # Web配置
  web:
    cors:
      allowed-origins: "http://localhost:3000,http://localhost:5173"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api
    # 文件上传配置
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

# 日志配置
logging:
  level:
    com.chatapp: DEBUG
    org.springframework.security: DEBUG
    org.mybatis: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"